### ISSUE TITLE
Create an example project

### ISSUE THREAD

**Issue by fwbrasil** [getclump/clump#44]
As mentioned here:

https://github.com/fwbrasil/clump/blob/3b53f76211612d125075fff1ac5db0bbd8bc28f1/README.md#example-project

cc/ @williamboxhall

**Comment by williamboxhall** [comment]
Would it be an end-to-end webapp? Can we use Zoot? What is zipball? :D

**Comment by fwbrasil** [comment]
I was thinking on an end-to-end Main class that outputs to the console using the SoundCloud's public api. Something simple just to show that Clump works and let people start testing it without much friction.

Zipball is the url that allows to generate a zip file for an entire repository.

Cool, lets use Zoot!

**Comment by fwbrasil** [comment]
closing this for now
