### ISSUE TITLE
Restrictive license

### ISSUE THREAD

**Issue by extesy** [getclump/clump#84]
Is there any chance you might adopt a less restrictive license like MIT, BSD or APL? Current license prevents it from being used in any commercial projects which don't have open-source business model.

**Comment by fwbrasil** [comment]
@extesy Could you provide more details? Note that LGPL is different from GPL and doesn't require derivative work to be open source. It is a `permissive` license, not `restrictive`

**Comment by extesy** [comment]
I've worked in several big companies and the conditions for using open source projects were almost always the same: if the license is MIT/BSD/Apache or comparable then I could use the library. Any *GPL license requires a long process involving corporate lawyers, business justification, paperwork, etc.

LGPL is better than GPL, that's true, but it's still in many cases inconvenient to use. Consider, for example, if I need to slightly tweak the library to accommodate our in-house implementation of thread pools which is used in all applications. With LGPL I have to make this tweak open-source. This might also mean open-sourcing our custom library too since it will be intertwined with our tweak. I think now you see the problem here.

**Comment by fwbrasil** [comment]
@extesy Thanks for the additional information. I've opened a pull request (#85) to change the license to Apache.

**Comment by fwbrasil** [comment]
Pull request merged.

**Comment by extesy** [comment]
Thank you for understanding, @fwbrasil!
