### ISSUE TITLE
Publish 0.0.14 to MavenCentral

### ISSUE THREAD

**Issue by ngbinh** [getclump/clump#96]
The latest version there is `0.0.12`: http://mvnrepository.com/artifact/io.getclump/clump-scala_2.11

**Comment by fwbrasil** [comment]
Actually this is the maven central repo: http://search.maven.org/#search%7Cga%7C1%7Cclump

It is missing the 0.0.14 version. @williamboxhall did you manage to publish it?

**Comment by williamboxhall** [comment]
This is now fixed: https://repo1.maven.org/maven2/io/getclump/clump-twitter_2.11/0.0.14/

**Comment by ngbinh** [comment]
:+1: thanks
